sort: 
  by: title
  sections: mixed
  ignore_case: true
  type: natural

not_in_nav: |
 old-link.md

hidden: 
 - old-link.md

nav:
 - index*.md
 - tutorial
 - guides
 - self-hosting
 - Entwicklungs- und API-Dokumentation: https://docs.pretix.eu/dev/
 - trust