sort: 
  by: title
  sections: mixed
  ignore_case: true
  type: natural

nav:
 - index*.md
 - tutorial
 - guides
 - self-hosting
 - Entwicklungs- und API-Dokumentation: https://docs.pretix.eu/dev/
 - trust

not_in_nav: |
 /old-link.md
